---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Duo Packages
  package:
    name: "{{ item }}"
    state: "{{ duo_pkgs_state }}"
  with_items: "{{ duo_pkgs }}"

- name: Create pam_duo configuration file(s)
  template:
    owner: root
    group: root
    mode: '0600'
    src: pam_duo.conf.j2
    dest: "{{ item.path }}"
  with_items: "{{ duo_pam_duo_confs }}"
  no_log: true
